### ISSUE TITLE
Failing to resolve assemblies on macOS

### ISSUE THREAD

**Issue by cederstrom** [microsoft/coyote-samples#39]
I'm trying to run the sample app ImageGalleryAspNet and I'm getting this reference error:

```bash
$ coyote rewrite rewrite.coyote.json
Microsoft (R) Coyote version 1.3.0.0 for .NET Core 5.0.0
Copyright (C) Microsoft Corporation. All rights reserved.

. Rewriting the assemblies specified in rewrite.coyote.json
... Copying all files to the '/Users/cederstrom/dev/labb/coyote/coyote-samples/WebApps/ImageGalleryAspNet/bin/coyote' directory
... Rewriting the 'ImageGalleryService.dll' assembly (ImageGalleryService, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
Unable to resolve assembly: Microsoft.Extensions.Hosting.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Failed to resolve assembly: 'Microsoft.Extensions.Hosting.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
... Rewriting the 'ImageGalleryTests.dll' assembly (ImageGalleryTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
Unable to resolve assembly: Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Failed to resolve assembly: 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
... Rewriting the 'TraceReplayer.dll' assembly (TraceReplayer, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null)
... Writing the modified 'TraceReplayer.dll' assembly to /Users/cederstrom/dev/labb/coyote/coyote-samples/WebApps/ImageGalleryAspNet/bin/coyote/TraceReplayer.dll
. Done rewriting in 0.427981 sec
```

Am I missing something?

My dotnet info:
```bash
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.302/

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  2.1.810 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]
  3.1.102 [/usr/local/share/dotnet/sdk]
  3.1.201 [/usr/local/share/dotnet/sdk]
  3.1.301 [/usr/local/share/dotnet/sdk]
  3.1.401 [/usr/local/share/dotnet/sdk]
  3.1.402 [/usr/local/share/dotnet/sdk]
  3.1.403 [/usr/local/share/dotnet/sdk]
  5.0.100 [/usr/local/share/dotnet/sdk]
  5.0.302 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.22 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.22 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by pdeligia** [comment]
Thanks for reporting this @cederstrom. I believe this should be benign and just a warning, if you see in the end it still says `Done rewriting in 0.427981 sec`. The issue arises I believe because it tries to resolve some system-level assemblies such as `Microsoft.Extensions.Logging.Abstractions` and does not find the location for them, but it should not really matter from the rewriters perspective. Could you try to run the tests after this rewriting step, and see if it still works for you?

**Comment by cederstrom** [comment]
@pdeligia You are correct! I just aborted when I got the big red failure message 🤦‍♂️

The test is working fine after the rewrite 👍

**Comment by shaya-pb** [comment]
I think this should be reopened. I'm getting the same error on Windows 10, and the tests are not running correctly either, they're throwing a ` Unhandled exception 'System.IO.FileNotFoundException' was thrown in 'ImageGalleryTests':   Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.` exception.

**Comment by pdeligia** [comment]
Thanks @shaya-pb for reporting, yes let me re-open this issue. This is a bit weird as it was working fine for me last time that I checked. Let us investigate.

Just to make sure, you did `coyote rewrite` and you were running the test on the rewritten dlls, right? (any rewritten dll should have the [IsAssemblyRewrittenAttribute](https://microsoft.github.io/coyote/#ref/Microsoft.Coyote.Rewriting/IsAssemblyRewrittenAttribute/IsAssemblyRewrittenAttribute/) attribute in its metadata, this can be checked with a tool like ildasm or ilspy)

Btw, yea, this is not the expected exception, usually this happens if either (1) the assemblies-under-test have not been rewritten as mentioned above, or (2) there is uncontrolled concurrency (e.g. coming from an assembly that cannot be rewritten such as some system library -- but typically Coyote will report an explicit error saying something about detected uncontrolled concurrency and propose a workaround), or (3) if there is a genuine deadlock (but this should not be the case here).

**Comment by shaya-pb** [comment]
Thanks @pdeligia - I'm not sure if something else isn't going on here with `dotnet test` and Coyote rewrites. I opened issue microsoft/coyote#219 on Coyote, that may be related.

**Comment by pdeligia** [comment]
Thanks @shaya-pb and @cederstrom. Just an update: we managed to identify and fix the issue. Basically the deadlock was happening because some of the assemblies where not rewritten properly (due to the assembly resolution error above), which then caused Coyote to not have full control of all the tasks in the test, resulting into a deadlock. The fix will be available in the next version of Coyote. Will close this issue when that happens.

**Comment by pdeligia** [comment]
Forgot to close this issue
