### ISSUE TITLE
Fixing the bug with leader election in Raft example - is this desired?

### ISSUE THREAD

**Issue by DylanSp** [microsoft/coyote-samples#8]
As documented, the Raft example has a bug with leader election, which can be discovered by running `coyote test` with the mock in `Raft.Nondeterminism`. This bug appears to be due to the way votes for a leader are counted; if messages from the same node are duplicated, they'll be registered as separate votes by `Server.VoteResponse()`. This bug can be fixed by tracking which nodes votes are coming from; however, I'm not sure if it's desirable to keep this bug around for demonstrating bugfinding. What's the maintainers' point of view on this?

**Comment by pdeligia** [comment]
Hi @DylanSp, apologies for the slow reply, this issue somehow escaped us! Thanks for asking about this: we indeed keep the bug there (in the `Raft.Nondeterminism` project) in purpose so that we can showcase the bug and how `coyote test` can find it. Whereas the `Raft.Mocking` is the same sample but without the bug. So I am closing this issue as a no-fix. Hope this answers your question.
